stages:  # 阶段
  - deploy

deploy_dev:
  stage: deploy
  only:  # 目前 CI 只对 develop、以 feature/.* 开头 和 以 feature-.* 开头分支有效
    - develop
    - /^feature\/.*$/
    - /^feature-.*$/
  tags: # CI tag 名称
    - dev
  script: # 构建命令
    - envsubst < Dockerfile | docker build -t $IMAGE -f - .
    - docker push $IMAGE
    - envsubst < app.dev.yaml | kubectl apply -f -
  variables: # 声明环境变量
    IMAGE: harbor.example.com/default/hello-world-$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
    SERVICE_NAME: hello-world-$CI_COMMIT_REF_SLUG
    NAMESPACE: default
    NODE_ENV: development
